/**
 * Things to try. Each one teaches a part of the weather, and the text says how,
 * so the journal doubles as the instructions.
 */
export const WISHES = [
  { id: 'first-bloom', text: 'Bring a plant into bloom.' },
  { id: 'three-at-once', text: 'Water three plants at once. Press X to spread the cloud wide.' },
  { id: 'wildflower', text: 'Blow seed into the lawn: hold Shift beside something in bloom.' },
  { id: 'rainbow', text: 'Make a rainbow: a good long shower while the sun is out.' },
  { id: 'fog', text: 'Wrap the ferns under the oak in fog. Press F.' },
  { id: 'lightning', text: 'Call down lightning: gather a full cloud tight (Z), then press L or double-click.' },
  { id: 'puddle', text: 'Rain on one spot until a puddle forms.' },
  { id: 'fairy-ring', text: 'Go back to a lightning scorch a little later and see what grew.' },
  { id: 'storm', text: 'Let a storm go with G once it has gathered. Greener grass gathers it faster.' },
  { id: 'green-half', text: 'Green half the lawn. Rain on dry grass and it stays green.' },
  { id: 'rainy-day', text: 'Call up a rainy day for the whole garden: press 3, or Rain at the bottom right.' },
  { id: 'snow', text: 'Let it snow in winter until the lawn is white.' },
  { id: 'leaves', text: 'Blow the autumn leaves about with a breeze.' },
  { id: 'four-seasons', text: 'See all four seasons come round.' },
  { id: 'rabbits', text: 'Green the lawn and the rabbits come out of their burrow to graze.' },
  { id: 'frogs', text: 'Bring the frogs out to croak: rain on the pond.' },
  { id: 'deer', text: 'Watch for the deer grazing beyond the back hedge at dawn or dusk.' },
  { id: 'tea', text: 'Give Rose and Walter a sunny afternoon for tea on the patio.' },
  { id: 'washing', text: 'Dry the washing on the line with sun and a breeze (Shift).' },
  { id: 'caught-out', text: 'Catch the washing out with a sudden shower.' },
  { id: 'harvest', text: 'Grow tomatoes, lettuce or apples for Walter to pick.' },
  { id: 'vase', text: 'Bloom enough lavender and sunflowers to fill the vase in the window.' },
  { id: 'snowman', text: 'Snow enough for Walter to build a snowman.' },
  { id: 'hedgehog', text: 'Rain in the evening, then watch for the hedgehog hunting slugs after dark.' },
  { id: 'kits', text: 'Keep the lawn lush in spring and the rabbits have kits.' },
  { id: 'chicks', text: 'Green the lawn in spring for chicks in the nest in the oak.' },
  { id: 'tadpoles', text: 'A wet spring fills the pond with tadpoles.' },
  { id: 'fawn', text: 'See the deer through a winter, and a fawn comes in spring.' },
  { id: 'second-hive', text: 'Bring ten flowers into bloom and the bees start a second hive.' },
  { id: 'sapling', text: 'An acorn the squirrels forget in autumn comes up as a sapling in spring.' },
  { id: 'geese', text: 'See the geese fly south in autumn.' },
  { id: 'apples', text: 'Grow apples. The blossom needs a breeze to set fruit.' },
  { id: 'sunflower', text: 'Grow a sunflower taller than the fence.' },
  { id: 'moonflower', text: 'Watch a moonflower open at night.' },
  { id: 'fireflies', text: 'Stay up after dark with ten wildflowers in the lawn.' },
  { id: 'meadow', text: 'Fill the lawn with sixty wildflowers.' },
  { id: 'all', text: 'Bring every plant in the garden into bloom.' },
] as const

export type WishId = (typeof WISHES)[number]['id']
